### ISSUE TITLE
There are certain accounts that are unscrapable

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/tweep#14]
I tried https://twitter.com/kimdotcom to test the installation, and it certainly works.  
However, https://twitter.com/a_fellow_white does not (flagged as"sensitive content")  
When I try to search his tweets, unless I am logged in, none of his tweets will show up.

**Comment by haccer** [comment]
I guess the only way to mitigate this would be to let people log in.

**Comment by pachonk** [comment]
Yeah, which would require you to build a Twitter session to avoid hitting
the Twitter api

**Comment by DonaldTsang** [comment]
While we are on the subject of "logging in", following and follows scraping could be done as well.

**Comment by pachonk** [comment]
I'm not sure that comment coincides with the purpose of this issue.

**Comment by haccer** [comment]
You can't access a person's followers or following via Twitter's search operators; I looked into scraping them a long time ago, the only way to do it involves some extensive selenium work which I don't want to do.

**Comment by DonaldTsang** [comment]
@haccer then how does that work with scrolling through the searches?

**Comment by haccer** [comment]
It's not technically scrolling, Tweep just iterates Tweet-IDs.

**Comment by haccer** [comment]
Thank you for providing an example of this, Donald.

Currently, Tweep cannot scrape Tweets belonging to accounts that require you to be logged in for their Tweets to be visible from Twitter's search (i.e Private Twitters, and Twitter accounts restricted by Twitter for potentially containing sensitive content). 

After careful thought, I've come to the conclusion that the only possible way to scrape Tweets belonging to these accounts would be to make authenticated requests. The only way to view these Tweets is by visiting the user's profile and clicking the link; however, this would not work with the program since you cannot iterate Tweets from the user's profile page like you can with Twitter's search. 

I've already experimented with scraping directly from a user's profile. Any work that would involve using selenium to emulate a browser I won't do because that affects performance and usually requires a browser to be open.

Maybe I will introduce authentication in the future, but for now I don't really plan on adding it. Introducing authentication invites more performance issues and comes with potential authenticating issues that won't be mitigatable (i.e Twitter accounts locking, 2 factor authentication). I would probably do it via passing cookies.

Thank you for the many suggestions Donald.

I'm going to close this because this isn't an issue with the program.
