### ISSUE TITLE
Output request: comment count, retweet count, favorite count, image permanent url

### ISSUE THREAD

**Issue by aaronmkchan** [haccer/tweep#25]
You're the man, Cody 🙏🏼

**Comment by haccer** [comment]
Added in latest [commit](https://github.com/haccer/tweep/commit/0dc66fdf8ccb9b65be4222cfebbf6c5500d897e0).

The image URL turned out to hinder performance, so for now I've included it in the new [dev branch](https://github.com/haccer/tweep/tree/dev) but not in the master while I continue working on it.
