### ISSUE TITLE
Why this gap between tweet posted and tweets downloaded. [no bug]

### ISSUE THREAD

**Issue by hpiedcoq** [haccer/tweep#32]
I don't think this is a bug, but I'm just wondering why is there such a gap between the number of tweets I'm supposed to have posted (+/- 1700) and the tweets I really download ( (+/- 770). 
Using the --count option was really disapointing on this point of view. Any idea about that?

**Comment by haccer** [comment]
Good question.

The total Tweet count on a user's profile includes their retweets as well, which I haven't figured out to get them to be displayed via Twitter search. 

That's why the amount of Tweets scraped is smaller than the number of Tweets on a users profile. 

There was an old [method](https://webapps.stackexchange.com/questions/52065/how-do-i-find-my-retweets-of-a-certain-account) to view retweets from the search bar, but it doesn't work. I've been experimenting w/ requests via Tweetdeck to see if I can figure out something new; but it seems that would require accessing the API.

**Comment by haccer** [comment]
There's also a few more factors:

In some cases if the user has changed their username, sometimes their previous Tweets from that old username won't be visible via the Twitter search.

I've also found that Twitter's search is also broken for certain users too, authenticated and unauthenticated.

**Comment by hpiedcoq** [comment]
I think I have a potential workaround for that... Let me code that a propose you a patch.
