### ISSUE TITLE
Install tweep

### ISSUE THREAD

**Issue by rexfan79** [haccer/tweep#33]
### Initial Check 
Make sure you've checked the following.

- [] Python version is 3.5 or higher.
- [] Using the latest version of Tweep.

### Command
Please provide the exact command ran including the username/search so I may reproduce the issue.

### Description of Issue
Please use as much detail as possible.

### OS Details
Using Windows, Linux? What OS version?

**Comment by rexfan79** [comment]
Hi, thanks for creating this. I am new to Github and would like to know how to install and use "tweep.py"? I tried to clone and download the library from Github, but did not find a way to use it on CL. I am using Windows 10 BTW. Thanks for help!

**Comment by lss4** [comment]
You need to download and install Python version 3.5 or higher for Windows from official Python site in order to use this script.

After installing Python, follow the readme.md's instructions (installing the required packages in pip, and how to use the script).

Note that you need to open an Administrator command prompt in order to perform pip3 package installations. The script itself does not require an administrator command prompt to run.
