### ISSUE TITLE
The scraping is stopping

### ISSUE THREAD

**Issue by naocaio** [haccer/tweep#60]
First of all, congratulations to your job, here in the university of goiás, brazil this code are helping us so much.
After you made some modifications and increase other comands i think something is going wrong and i wanna know if you can help me. 
For example the string: python3 tweep.py -s "bolsonaro2018" --since 2018-01-01 -o testbolsonaro.csv --csv is stopping on date 2018-04-03, i already tried on windows 10 and ubuntu 17.10 with the actually version of tweep and others ago. 
Thanks

**Comment by haccer** [comment]
This looks related to [issue #48](https://github.com/haccer/tweep/issues/48). 

Due to what appears to be a Tweet search limit, you'll have to scrape using weekly increments by using `--until` and `--since`. 

I've been meaning to add a way to automate this for searches that contain a lot of Tweets.
